- name: Configure SSH for mgmt user
  block:
    - name: Disable SSH password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        validate: 'sshd -T -f %s'
      notify: restart sshd
